### ISSUE TITLE
README 缺少对「理解最好」的详细说明

### ISSUE THREAD

**Issue by Justineo** [yanhaijing/lodjs#1]
RT.

**Comment by leeight** [comment]
+1

**Comment by yanhaijing** [comment]
lodjs 对于依赖的解析全部基于当前js，这让事情变得更简单。
定义有名模块时，.js结尾不会报错
首创的 BASEURL和DOCURL可以解析到任何路径

**Comment by Justineo** [comment]
期待有些例子对比一下 :)

**Comment by yanhaijing** [comment]
其实这句话只说了一半，缺少了后半句：迄今为止，对AMD理解最好的实现，在我看来
